### ISSUE TITLE
Missing requiriment: Clustering

### ISSUE THREAD

**Issue by cdsousa** [cormullion/ColorSchemes.jl#1]
INFO: Precompiling module ColorSchemes...
    ERROR: LoadError: ArgumentError: Clustering not found in path

**Comment by cdsousa** [comment]
And also Images and Colors...

**Comment by cormullion** [comment]
@cdsousa Oops. I keep forgetting that... :)

**Comment by cdsousa** [comment]
;) I guess it is really common to happen
